/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as pharmacyDashboardRouteImport } from './routes/(pharmacy)/dashboard'
import { Route as pharmacyInventoryRouteImport } from './routes/(pharmacy)/inventory'
import { Route as pharmacyMarketplaceRouteImport } from './routes/(pharmacy)/marketplace'
import { Route as pharmacyOrdersRouteImport } from './routes/(pharmacy)/orders'
import { Route as pharmacyPosRouteImport } from './routes/(pharmacy)/pos'
import { Route as pharmacyProfileRouteImport } from './routes/(pharmacy)/profile'
import { Route as pharmacyPurchaseOrdersRouteImport } from './routes/(pharmacy)/purchase-orders'
import { Route as pharmacyReportsRouteImport } from './routes/(pharmacy)/reports'
import { Route as pharmacySalesRouteImport } from './routes/(pharmacy)/sales'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminLogsRouteImport } from './routes/admin/logs'
import { Route as AdminPayoutRouteImport } from './routes/admin/payout'
import { Route as AdminPharmaciesRouteImport } from './routes/admin/pharmacies'
import { Route as AdminProductsRouteImport } from './routes/admin/products'
import { Route as AdminProfileRouteImport } from './routes/admin/profile'
import { Route as AdminRegisterRouteImport } from './routes/admin/register'
import { Route as AdminReportsRouteImport } from './routes/admin/reports'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminSupportRouteImport } from './routes/admin/support'
import { Route as AdminTeamRouteImport } from './routes/admin/team'
import { Route as SupplierIndexRouteImport } from './routes/supplier/index'
import { Route as SupplierDashboardRouteImport } from './routes/supplier/dashboard'
import { Route as SupplierIncomingOrdersRouteImport } from './routes/supplier/incoming-orders'
import { Route as SupplierInventoryRouteImport } from './routes/supplier/inventory'
import { Route as SupplierProfileRouteImport } from './routes/supplier/profile'
import { Route as SupplierReportsRouteImport } from './routes/supplier/reports'
import { Route as SupplierRoutRouteImport } from './routes/supplier/rout'
import { Route as SupplierSalesHistoryRouteImport } from './routes/supplier/sales-history'
import { Route as pharmacyInventoryAddRouteImport } from './routes/(pharmacy)/inventory_.add'
import { Route as pharmacyStaffAddRouteImport } from './routes/(pharmacy)/staff.add'
import { Route as AdminPharmaciesPharmacyIdRouteImport } from './routes/admin/pharmacies_.$pharmacyId'
import { Route as pharmacyInventoryAddProductIdRouteImport } from './routes/(pharmacy)/inventory_.add_.$productId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const pharmacyDashboardRoute = pharmacyDashboardRouteImport.update({
  id: '/(pharmacy)/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const pharmacyInventoryRoute = pharmacyInventoryRouteImport.update({
  id: '/(pharmacy)/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const pharmacyMarketplaceRoute = pharmacyMarketplaceRouteImport.update({
  id: '/(pharmacy)/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const pharmacyOrdersRoute = pharmacyOrdersRouteImport.update({
  id: '/(pharmacy)/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const pharmacyPosRoute = pharmacyPosRouteImport.update({
  id: '/(pharmacy)/pos',
  path: '/pos',
  getParentRoute: () => rootRouteImport,
} as any)
const pharmacyProfileRoute = pharmacyProfileRouteImport.update({
  id: '/(pharmacy)/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const pharmacyPurchaseOrdersRoute = pharmacyPurchaseOrdersRouteImport.update({
  id: '/(pharmacy)/purchase-orders',
  path: '/purchase-orders',
  getParentRoute: () => rootRouteImport,
} as any)
const pharmacyReportsRoute = pharmacyReportsRouteImport.update({
  id: '/(pharmacy)/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const pharmacySalesRoute = pharmacySalesRouteImport.update({
  id: '/(pharmacy)/sales',
  path: '/sales',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLogsRoute = AdminLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPayoutRoute = AdminPayoutRouteImport.update({
  id: '/payout',
  path: '/payout',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPharmaciesRoute = AdminPharmaciesRouteImport.update({
  id: '/pharmacies',
  path: '/pharmacies',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminProfileRoute = AdminProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminRegisterRoute = AdminRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSupportRoute = AdminSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminTeamRoute = AdminTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AdminRouteRoute,
} as any)
const SupplierIndexRoute = SupplierIndexRouteImport.update({
  id: '/supplier/',
  path: '/supplier/',
  getParentRoute: () => rootRouteImport,
} as any)
const SupplierDashboardRoute = SupplierDashboardRouteImport.update({
  id: '/supplier/dashboard',
  path: '/supplier/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const SupplierIncomingOrdersRoute = SupplierIncomingOrdersRouteImport.update({
  id: '/supplier/incoming-orders',
  path: '/supplier/incoming-orders',
  getParentRoute: () => rootRouteImport,
} as any)
const SupplierInventoryRoute = SupplierInventoryRouteImport.update({
  id: '/supplier/inventory',
  path: '/supplier/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const SupplierProfileRoute = SupplierProfileRouteImport.update({
  id: '/supplier/profile',
  path: '/supplier/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SupplierReportsRoute = SupplierReportsRouteImport.update({
  id: '/supplier/reports',
  path: '/supplier/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const SupplierRoutRoute = SupplierRoutRouteImport.update({
  id: '/supplier/rout',
  path: '/supplier/rout',
  getParentRoute: () => rootRouteImport,
} as any)
const SupplierSalesHistoryRoute = SupplierSalesHistoryRouteImport.update({
  id: '/supplier/sales-history',
  path: '/supplier/sales-history',
  getParentRoute: () => rootRouteImport,
} as any)
const pharmacyInventoryAddRoute = pharmacyInventoryAddRouteImport.update({
  id: '/(pharmacy)/inventory_/add',
  path: '/inventory/add',
  getParentRoute: () => rootRouteImport,
} as any)
const pharmacyStaffAddRoute = pharmacyStaffAddRouteImport.update({
  id: '/(pharmacy)/staff/add',
  path: '/staff/add',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPharmaciesPharmacyIdRoute =
  AdminPharmaciesPharmacyIdRouteImport.update({
    id: '/pharmacies_/$pharmacyId',
    path: '/pharmacies/$pharmacyId',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const pharmacyInventoryAddProductIdRoute =
  pharmacyInventoryAddProductIdRouteImport.update({
    id: '/(pharmacy)/inventory_/add_/$productId',
    path: '/inventory/add/$productId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/contact': typeof ContactRoute
  '/features': typeof FeaturesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard': typeof pharmacyDashboardRoute
  '/inventory': typeof pharmacyInventoryRoute
  '/marketplace': typeof pharmacyMarketplaceRoute
  '/orders': typeof pharmacyOrdersRoute
  '/pos': typeof pharmacyPosRoute
  '/profile': typeof pharmacyProfileRoute
  '/purchase-orders': typeof pharmacyPurchaseOrdersRoute
  '/reports': typeof pharmacyReportsRoute
  '/sales': typeof pharmacySalesRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/payout': typeof AdminPayoutRoute
  '/admin/pharmacies': typeof AdminPharmaciesRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/register': typeof AdminRegisterRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/team': typeof AdminTeamRoute
  '/supplier/dashboard': typeof SupplierDashboardRoute
  '/supplier/incoming-orders': typeof SupplierIncomingOrdersRoute
  '/supplier/inventory': typeof SupplierInventoryRoute
  '/supplier/profile': typeof SupplierProfileRoute
  '/supplier/reports': typeof SupplierReportsRoute
  '/supplier/rout': typeof SupplierRoutRoute
  '/supplier/sales-history': typeof SupplierSalesHistoryRoute
  '/admin/': typeof AdminIndexRoute
  '/supplier/': typeof SupplierIndexRoute
  '/inventory/add': typeof pharmacyInventoryAddRoute
  '/staff/add': typeof pharmacyStaffAddRoute
  '/admin/pharmacies/$pharmacyId': typeof AdminPharmaciesPharmacyIdRoute
  '/inventory/add/$productId': typeof pharmacyInventoryAddProductIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/features': typeof FeaturesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard': typeof pharmacyDashboardRoute
  '/inventory': typeof pharmacyInventoryRoute
  '/marketplace': typeof pharmacyMarketplaceRoute
  '/orders': typeof pharmacyOrdersRoute
  '/pos': typeof pharmacyPosRoute
  '/profile': typeof pharmacyProfileRoute
  '/purchase-orders': typeof pharmacyPurchaseOrdersRoute
  '/reports': typeof pharmacyReportsRoute
  '/sales': typeof pharmacySalesRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/payout': typeof AdminPayoutRoute
  '/admin/pharmacies': typeof AdminPharmaciesRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/register': typeof AdminRegisterRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/team': typeof AdminTeamRoute
  '/supplier/dashboard': typeof SupplierDashboardRoute
  '/supplier/incoming-orders': typeof SupplierIncomingOrdersRoute
  '/supplier/inventory': typeof SupplierInventoryRoute
  '/supplier/profile': typeof SupplierProfileRoute
  '/supplier/reports': typeof SupplierReportsRoute
  '/supplier/rout': typeof SupplierRoutRoute
  '/supplier/sales-history': typeof SupplierSalesHistoryRoute
  '/admin': typeof AdminIndexRoute
  '/supplier': typeof SupplierIndexRoute
  '/inventory/add': typeof pharmacyInventoryAddRoute
  '/staff/add': typeof pharmacyStaffAddRoute
  '/admin/pharmacies/$pharmacyId': typeof AdminPharmaciesPharmacyIdRoute
  '/inventory/add/$productId': typeof pharmacyInventoryAddProductIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/contact': typeof ContactRoute
  '/features': typeof FeaturesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/(pharmacy)/dashboard': typeof pharmacyDashboardRoute
  '/(pharmacy)/inventory': typeof pharmacyInventoryRoute
  '/(pharmacy)/marketplace': typeof pharmacyMarketplaceRoute
  '/(pharmacy)/orders': typeof pharmacyOrdersRoute
  '/(pharmacy)/pos': typeof pharmacyPosRoute
  '/(pharmacy)/profile': typeof pharmacyProfileRoute
  '/(pharmacy)/purchase-orders': typeof pharmacyPurchaseOrdersRoute
  '/(pharmacy)/reports': typeof pharmacyReportsRoute
  '/(pharmacy)/sales': typeof pharmacySalesRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/payout': typeof AdminPayoutRoute
  '/admin/pharmacies': typeof AdminPharmaciesRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/register': typeof AdminRegisterRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/team': typeof AdminTeamRoute
  '/supplier/dashboard': typeof SupplierDashboardRoute
  '/supplier/incoming-orders': typeof SupplierIncomingOrdersRoute
  '/supplier/inventory': typeof SupplierInventoryRoute
  '/supplier/profile': typeof SupplierProfileRoute
  '/supplier/reports': typeof SupplierReportsRoute
  '/supplier/rout': typeof SupplierRoutRoute
  '/supplier/sales-history': typeof SupplierSalesHistoryRoute
  '/admin/': typeof AdminIndexRoute
  '/supplier/': typeof SupplierIndexRoute
  '/(pharmacy)/inventory_/add': typeof pharmacyInventoryAddRoute
  '/(pharmacy)/staff/add': typeof pharmacyStaffAddRoute
  '/admin/pharmacies_/$pharmacyId': typeof AdminPharmaciesPharmacyIdRoute
  '/(pharmacy)/inventory_/add_/$productId': typeof pharmacyInventoryAddProductIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/contact'
    | '/features'
    | '/forgot-password'
    | '/login'
    | '/pricing'
    | '/register'
    | '/reset-password'
    | '/dashboard'
    | '/inventory'
    | '/marketplace'
    | '/orders'
    | '/pos'
    | '/profile'
    | '/purchase-orders'
    | '/reports'
    | '/sales'
    | '/admin/logs'
    | '/admin/payout'
    | '/admin/pharmacies'
    | '/admin/products'
    | '/admin/profile'
    | '/admin/register'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/support'
    | '/admin/team'
    | '/supplier/dashboard'
    | '/supplier/incoming-orders'
    | '/supplier/inventory'
    | '/supplier/profile'
    | '/supplier/reports'
    | '/supplier/rout'
    | '/supplier/sales-history'
    | '/admin/'
    | '/supplier/'
    | '/inventory/add'
    | '/staff/add'
    | '/admin/pharmacies/$pharmacyId'
    | '/inventory/add/$productId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/features'
    | '/forgot-password'
    | '/login'
    | '/pricing'
    | '/register'
    | '/reset-password'
    | '/dashboard'
    | '/inventory'
    | '/marketplace'
    | '/orders'
    | '/pos'
    | '/profile'
    | '/purchase-orders'
    | '/reports'
    | '/sales'
    | '/admin/logs'
    | '/admin/payout'
    | '/admin/pharmacies'
    | '/admin/products'
    | '/admin/profile'
    | '/admin/register'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/support'
    | '/admin/team'
    | '/supplier/dashboard'
    | '/supplier/incoming-orders'
    | '/supplier/inventory'
    | '/supplier/profile'
    | '/supplier/reports'
    | '/supplier/rout'
    | '/supplier/sales-history'
    | '/admin'
    | '/supplier'
    | '/inventory/add'
    | '/staff/add'
    | '/admin/pharmacies/$pharmacyId'
    | '/inventory/add/$productId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/contact'
    | '/features'
    | '/forgot-password'
    | '/login'
    | '/pricing'
    | '/register'
    | '/reset-password'
    | '/(pharmacy)/dashboard'
    | '/(pharmacy)/inventory'
    | '/(pharmacy)/marketplace'
    | '/(pharmacy)/orders'
    | '/(pharmacy)/pos'
    | '/(pharmacy)/profile'
    | '/(pharmacy)/purchase-orders'
    | '/(pharmacy)/reports'
    | '/(pharmacy)/sales'
    | '/admin/logs'
    | '/admin/payout'
    | '/admin/pharmacies'
    | '/admin/products'
    | '/admin/profile'
    | '/admin/register'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/support'
    | '/admin/team'
    | '/supplier/dashboard'
    | '/supplier/incoming-orders'
    | '/supplier/inventory'
    | '/supplier/profile'
    | '/supplier/reports'
    | '/supplier/rout'
    | '/supplier/sales-history'
    | '/admin/'
    | '/supplier/'
    | '/(pharmacy)/inventory_/add'
    | '/(pharmacy)/staff/add'
    | '/admin/pharmacies_/$pharmacyId'
    | '/(pharmacy)/inventory_/add_/$productId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  ContactRoute: typeof ContactRoute
  FeaturesRoute: typeof FeaturesRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  pharmacyDashboardRoute: typeof pharmacyDashboardRoute
  pharmacyInventoryRoute: typeof pharmacyInventoryRoute
  pharmacyMarketplaceRoute: typeof pharmacyMarketplaceRoute
  pharmacyOrdersRoute: typeof pharmacyOrdersRoute
  pharmacyPosRoute: typeof pharmacyPosRoute
  pharmacyProfileRoute: typeof pharmacyProfileRoute
  pharmacyPurchaseOrdersRoute: typeof pharmacyPurchaseOrdersRoute
  pharmacyReportsRoute: typeof pharmacyReportsRoute
  pharmacySalesRoute: typeof pharmacySalesRoute
  SupplierDashboardRoute: typeof SupplierDashboardRoute
  SupplierIncomingOrdersRoute: typeof SupplierIncomingOrdersRoute
  SupplierInventoryRoute: typeof SupplierInventoryRoute
  SupplierProfileRoute: typeof SupplierProfileRoute
  SupplierReportsRoute: typeof SupplierReportsRoute
  SupplierRoutRoute: typeof SupplierRoutRoute
  SupplierSalesHistoryRoute: typeof SupplierSalesHistoryRoute
  SupplierIndexRoute: typeof SupplierIndexRoute
  pharmacyInventoryAddRoute: typeof pharmacyInventoryAddRoute
  pharmacyStaffAddRoute: typeof pharmacyStaffAddRoute
  pharmacyInventoryAddProductIdRoute: typeof pharmacyInventoryAddProductIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(pharmacy)/dashboard': {
      id: '/(pharmacy)/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof pharmacyDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(pharmacy)/inventory': {
      id: '/(pharmacy)/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof pharmacyInventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(pharmacy)/marketplace': {
      id: '/(pharmacy)/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof pharmacyMarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(pharmacy)/orders': {
      id: '/(pharmacy)/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof pharmacyOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(pharmacy)/pos': {
      id: '/(pharmacy)/pos'
      path: '/pos'
      fullPath: '/pos'
      preLoaderRoute: typeof pharmacyPosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(pharmacy)/profile': {
      id: '/(pharmacy)/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof pharmacyProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(pharmacy)/purchase-orders': {
      id: '/(pharmacy)/purchase-orders'
      path: '/purchase-orders'
      fullPath: '/purchase-orders'
      preLoaderRoute: typeof pharmacyPurchaseOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(pharmacy)/reports': {
      id: '/(pharmacy)/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof pharmacyReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(pharmacy)/sales': {
      id: '/(pharmacy)/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof pharmacySalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/logs': {
      id: '/admin/logs'
      path: '/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof AdminLogsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/payout': {
      id: '/admin/payout'
      path: '/payout'
      fullPath: '/admin/payout'
      preLoaderRoute: typeof AdminPayoutRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/pharmacies': {
      id: '/admin/pharmacies'
      path: '/pharmacies'
      fullPath: '/admin/pharmacies'
      preLoaderRoute: typeof AdminPharmaciesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/profile': {
      id: '/admin/profile'
      path: '/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AdminProfileRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/register': {
      id: '/admin/register'
      path: '/register'
      fullPath: '/admin/register'
      preLoaderRoute: typeof AdminRegisterRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/support': {
      id: '/admin/support'
      path: '/support'
      fullPath: '/admin/support'
      preLoaderRoute: typeof AdminSupportRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/team': {
      id: '/admin/team'
      path: '/team'
      fullPath: '/admin/team'
      preLoaderRoute: typeof AdminTeamRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/supplier/': {
      id: '/supplier/'
      path: '/supplier'
      fullPath: '/supplier/'
      preLoaderRoute: typeof SupplierIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supplier/dashboard': {
      id: '/supplier/dashboard'
      path: '/supplier/dashboard'
      fullPath: '/supplier/dashboard'
      preLoaderRoute: typeof SupplierDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supplier/incoming-orders': {
      id: '/supplier/incoming-orders'
      path: '/supplier/incoming-orders'
      fullPath: '/supplier/incoming-orders'
      preLoaderRoute: typeof SupplierIncomingOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supplier/inventory': {
      id: '/supplier/inventory'
      path: '/supplier/inventory'
      fullPath: '/supplier/inventory'
      preLoaderRoute: typeof SupplierInventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supplier/profile': {
      id: '/supplier/profile'
      path: '/supplier/profile'
      fullPath: '/supplier/profile'
      preLoaderRoute: typeof SupplierProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supplier/reports': {
      id: '/supplier/reports'
      path: '/supplier/reports'
      fullPath: '/supplier/reports'
      preLoaderRoute: typeof SupplierReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supplier/rout': {
      id: '/supplier/rout'
      path: '/supplier/rout'
      fullPath: '/supplier/rout'
      preLoaderRoute: typeof SupplierRoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supplier/sales-history': {
      id: '/supplier/sales-history'
      path: '/supplier/sales-history'
      fullPath: '/supplier/sales-history'
      preLoaderRoute: typeof SupplierSalesHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(pharmacy)/inventory_/add': {
      id: '/(pharmacy)/inventory_/add'
      path: '/inventory/add'
      fullPath: '/inventory/add'
      preLoaderRoute: typeof pharmacyInventoryAddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(pharmacy)/staff/add': {
      id: '/(pharmacy)/staff/add'
      path: '/staff/add'
      fullPath: '/staff/add'
      preLoaderRoute: typeof pharmacyStaffAddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/pharmacies_/$pharmacyId': {
      id: '/admin/pharmacies_/$pharmacyId'
      path: '/pharmacies/$pharmacyId'
      fullPath: '/admin/pharmacies/$pharmacyId'
      preLoaderRoute: typeof AdminPharmaciesPharmacyIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/(pharmacy)/inventory_/add_/$productId': {
      id: '/(pharmacy)/inventory_/add_/$productId'
      path: '/inventory/add/$productId'
      fullPath: '/inventory/add/$productId'
      preLoaderRoute: typeof pharmacyInventoryAddProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteRouteChildren {
  AdminLogsRoute: typeof AdminLogsRoute
  AdminPayoutRoute: typeof AdminPayoutRoute
  AdminPharmaciesRoute: typeof AdminPharmaciesRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminProfileRoute: typeof AdminProfileRoute
  AdminRegisterRoute: typeof AdminRegisterRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSupportRoute: typeof AdminSupportRoute
  AdminTeamRoute: typeof AdminTeamRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminPharmaciesPharmacyIdRoute: typeof AdminPharmaciesPharmacyIdRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminLogsRoute: AdminLogsRoute,
  AdminPayoutRoute: AdminPayoutRoute,
  AdminPharmaciesRoute: AdminPharmaciesRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminProfileRoute: AdminProfileRoute,
  AdminRegisterRoute: AdminRegisterRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSupportRoute: AdminSupportRoute,
  AdminTeamRoute: AdminTeamRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminPharmaciesPharmacyIdRoute: AdminPharmaciesPharmacyIdRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  ContactRoute: ContactRoute,
  FeaturesRoute: FeaturesRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  pharmacyDashboardRoute: pharmacyDashboardRoute,
  pharmacyInventoryRoute: pharmacyInventoryRoute,
  pharmacyMarketplaceRoute: pharmacyMarketplaceRoute,
  pharmacyOrdersRoute: pharmacyOrdersRoute,
  pharmacyPosRoute: pharmacyPosRoute,
  pharmacyProfileRoute: pharmacyProfileRoute,
  pharmacyPurchaseOrdersRoute: pharmacyPurchaseOrdersRoute,
  pharmacyReportsRoute: pharmacyReportsRoute,
  pharmacySalesRoute: pharmacySalesRoute,
  SupplierDashboardRoute: SupplierDashboardRoute,
  SupplierIncomingOrdersRoute: SupplierIncomingOrdersRoute,
  SupplierInventoryRoute: SupplierInventoryRoute,
  SupplierProfileRoute: SupplierProfileRoute,
  SupplierReportsRoute: SupplierReportsRoute,
  SupplierRoutRoute: SupplierRoutRoute,
  SupplierSalesHistoryRoute: SupplierSalesHistoryRoute,
  SupplierIndexRoute: SupplierIndexRoute,
  pharmacyInventoryAddRoute: pharmacyInventoryAddRoute,
  pharmacyStaffAddRoute: pharmacyStaffAddRoute,
  pharmacyInventoryAddProductIdRoute: pharmacyInventoryAddProductIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
