/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PosRouteImport } from './routes/pos'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as StaffAddRouteImport } from './routes/staff.add'
import { Route as InventoryAddRouteImport } from './routes/inventory_.add'
import { Route as AdminTeamRouteImport } from './routes/admin.team'
import { Route as AdminSupportRouteImport } from './routes/admin.support'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminRegisterRouteImport } from './routes/admin.register'
import { Route as AdminProfileRouteImport } from './routes/admin.profile'
import { Route as AdminProductsRouteImport } from './routes/admin.products'
import { Route as AdminPharmaciesRouteImport } from './routes/admin.pharmacies'
import { Route as AdminPayoutRouteImport } from './routes/admin.payout'
import { Route as AdminLogsRouteImport } from './routes/admin.logs'
import { Route as InventoryAddProductIdRouteImport } from './routes/inventory_.add_.$productId'
import { Route as AdminPharmaciesPharmacyIdRouteImport } from './routes/admin.pharmacies_.$pharmacyId'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PosRoute = PosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const StaffAddRoute = StaffAddRouteImport.update({
  id: '/staff/add',
  path: '/staff/add',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryAddRoute = InventoryAddRouteImport.update({
  id: '/inventory_/add',
  path: '/inventory/add',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTeamRoute = AdminTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSupportRoute = AdminSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRegisterRoute = AdminRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProfileRoute = AdminProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPharmaciesRoute = AdminPharmaciesRouteImport.update({
  id: '/pharmacies',
  path: '/pharmacies',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPayoutRoute = AdminPayoutRouteImport.update({
  id: '/payout',
  path: '/payout',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLogsRoute = AdminLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AdminRoute,
} as any)
const InventoryAddProductIdRoute = InventoryAddProductIdRouteImport.update({
  id: '/inventory_/add_/$productId',
  path: '/inventory/add/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPharmaciesPharmacyIdRoute =
  AdminPharmaciesPharmacyIdRouteImport.update({
    id: '/pharmacies_/$pharmacyId',
    path: '/pharmacies/$pharmacyId',
    getParentRoute: () => AdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/features': typeof FeaturesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/pos': typeof PosRoute
  '/pricing': typeof PricingRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/reports': typeof ReportsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/payout': typeof AdminPayoutRoute
  '/admin/pharmacies': typeof AdminPharmaciesRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/register': typeof AdminRegisterRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/team': typeof AdminTeamRoute
  '/inventory/add': typeof InventoryAddRoute
  '/staff/add': typeof StaffAddRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/pharmacies/$pharmacyId': typeof AdminPharmaciesPharmacyIdRoute
  '/inventory/add/$productId': typeof InventoryAddProductIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/features': typeof FeaturesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/pos': typeof PosRoute
  '/pricing': typeof PricingRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/reports': typeof ReportsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/payout': typeof AdminPayoutRoute
  '/admin/pharmacies': typeof AdminPharmaciesRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/register': typeof AdminRegisterRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/team': typeof AdminTeamRoute
  '/inventory/add': typeof InventoryAddRoute
  '/staff/add': typeof StaffAddRoute
  '/admin': typeof AdminIndexRoute
  '/admin/pharmacies/$pharmacyId': typeof AdminPharmaciesPharmacyIdRoute
  '/inventory/add/$productId': typeof InventoryAddProductIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/features': typeof FeaturesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/pos': typeof PosRoute
  '/pricing': typeof PricingRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/reports': typeof ReportsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/payout': typeof AdminPayoutRoute
  '/admin/pharmacies': typeof AdminPharmaciesRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/register': typeof AdminRegisterRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/team': typeof AdminTeamRoute
  '/inventory_/add': typeof InventoryAddRoute
  '/staff/add': typeof StaffAddRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/pharmacies_/$pharmacyId': typeof AdminPharmaciesPharmacyIdRoute
  '/inventory_/add_/$productId': typeof InventoryAddProductIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/contact'
    | '/dashboard'
    | '/features'
    | '/forgot-password'
    | '/inventory'
    | '/login'
    | '/pos'
    | '/pricing'
    | '/profile'
    | '/register'
    | '/reports'
    | '/reset-password'
    | '/admin/logs'
    | '/admin/payout'
    | '/admin/pharmacies'
    | '/admin/products'
    | '/admin/profile'
    | '/admin/register'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/support'
    | '/admin/team'
    | '/inventory/add'
    | '/staff/add'
    | '/admin/'
    | '/admin/pharmacies/$pharmacyId'
    | '/inventory/add/$productId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/dashboard'
    | '/features'
    | '/forgot-password'
    | '/inventory'
    | '/login'
    | '/pos'
    | '/pricing'
    | '/profile'
    | '/register'
    | '/reports'
    | '/reset-password'
    | '/admin/logs'
    | '/admin/payout'
    | '/admin/pharmacies'
    | '/admin/products'
    | '/admin/profile'
    | '/admin/register'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/support'
    | '/admin/team'
    | '/inventory/add'
    | '/staff/add'
    | '/admin'
    | '/admin/pharmacies/$pharmacyId'
    | '/inventory/add/$productId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/contact'
    | '/dashboard'
    | '/features'
    | '/forgot-password'
    | '/inventory'
    | '/login'
    | '/pos'
    | '/pricing'
    | '/profile'
    | '/register'
    | '/reports'
    | '/reset-password'
    | '/admin/logs'
    | '/admin/payout'
    | '/admin/pharmacies'
    | '/admin/products'
    | '/admin/profile'
    | '/admin/register'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/support'
    | '/admin/team'
    | '/inventory_/add'
    | '/staff/add'
    | '/admin/'
    | '/admin/pharmacies_/$pharmacyId'
    | '/inventory_/add_/$productId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  FeaturesRoute: typeof FeaturesRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  InventoryRoute: typeof InventoryRoute
  LoginRoute: typeof LoginRoute
  PosRoute: typeof PosRoute
  PricingRoute: typeof PricingRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  ReportsRoute: typeof ReportsRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  InventoryAddRoute: typeof InventoryAddRoute
  StaffAddRoute: typeof StaffAddRoute
  InventoryAddProductIdRoute: typeof InventoryAddProductIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pos': {
      id: '/pos'
      path: '/pos'
      fullPath: '/pos'
      preLoaderRoute: typeof PosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/staff/add': {
      id: '/staff/add'
      path: '/staff/add'
      fullPath: '/staff/add'
      preLoaderRoute: typeof StaffAddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory_/add': {
      id: '/inventory_/add'
      path: '/inventory/add'
      fullPath: '/inventory/add'
      preLoaderRoute: typeof InventoryAddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/team': {
      id: '/admin/team'
      path: '/team'
      fullPath: '/admin/team'
      preLoaderRoute: typeof AdminTeamRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/support': {
      id: '/admin/support'
      path: '/support'
      fullPath: '/admin/support'
      preLoaderRoute: typeof AdminSupportRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/register': {
      id: '/admin/register'
      path: '/register'
      fullPath: '/admin/register'
      preLoaderRoute: typeof AdminRegisterRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/profile': {
      id: '/admin/profile'
      path: '/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AdminProfileRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pharmacies': {
      id: '/admin/pharmacies'
      path: '/pharmacies'
      fullPath: '/admin/pharmacies'
      preLoaderRoute: typeof AdminPharmaciesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payout': {
      id: '/admin/payout'
      path: '/payout'
      fullPath: '/admin/payout'
      preLoaderRoute: typeof AdminPayoutRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/logs': {
      id: '/admin/logs'
      path: '/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof AdminLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/inventory_/add_/$productId': {
      id: '/inventory_/add_/$productId'
      path: '/inventory/add/$productId'
      fullPath: '/inventory/add/$productId'
      preLoaderRoute: typeof InventoryAddProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/pharmacies_/$pharmacyId': {
      id: '/admin/pharmacies_/$pharmacyId'
      path: '/pharmacies/$pharmacyId'
      fullPath: '/admin/pharmacies/$pharmacyId'
      preLoaderRoute: typeof AdminPharmaciesPharmacyIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminLogsRoute: typeof AdminLogsRoute
  AdminPayoutRoute: typeof AdminPayoutRoute
  AdminPharmaciesRoute: typeof AdminPharmaciesRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminProfileRoute: typeof AdminProfileRoute
  AdminRegisterRoute: typeof AdminRegisterRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSupportRoute: typeof AdminSupportRoute
  AdminTeamRoute: typeof AdminTeamRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminPharmaciesPharmacyIdRoute: typeof AdminPharmaciesPharmacyIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminLogsRoute: AdminLogsRoute,
  AdminPayoutRoute: AdminPayoutRoute,
  AdminPharmaciesRoute: AdminPharmaciesRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminProfileRoute: AdminProfileRoute,
  AdminRegisterRoute: AdminRegisterRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSupportRoute: AdminSupportRoute,
  AdminTeamRoute: AdminTeamRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminPharmaciesPharmacyIdRoute: AdminPharmaciesPharmacyIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  FeaturesRoute: FeaturesRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  InventoryRoute: InventoryRoute,
  LoginRoute: LoginRoute,
  PosRoute: PosRoute,
  PricingRoute: PricingRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  ReportsRoute: ReportsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  InventoryAddRoute: InventoryAddRoute,
  StaffAddRoute: StaffAddRoute,
  InventoryAddProductIdRoute: InventoryAddProductIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
